name: Extract Version from package.json

on:
  push:
    branches:
      - main

jobs:
  extract_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version
        id: extract-version
        run: echo "version=$(cat package.json | jq -r '.version')" >> "$GITHUB_OUTPUT"

      - name: Print version
        run: echo ${{ steps.extract-version.outputs.version }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vocoront/simple-express-server:${{ steps.extract-version.outputs.version }}

      - name: Update instance
        id: updaing-instance
        uses: decent-infra/shomix-car-update-action@v1.0
        with:
          spheron-token:  ${{ secrets.SPHERON_TOKEN }}
          instance-id: "6469132102397f001249ca6c"
          tag: ${{ steps.extract-version.outputs.version }}