name: Extract Version from package.json

on:
  push:
    branches:
      - main

jobs:
  extract_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version
        run: echo "::set-output name=version::$(cat package.json | jq -r '.version')"

      - name: Print version
        run: echo "Version: ${{ steps.extract_version.outputs.version }}"
